version: '3.1'
services:
  redis:
    image: 'redis:alpine'

  mysql:
    image: 'mysql:8.0'
    working_dir: /iclinic
    volumes:
      - '.:/iclinic'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"

  webserver:
    image: 'nginx:alpine'
    working_dir: /iclinic
    volumes:
      - '.:/iclinic'
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - "${WEBSERVER_PORT}:80"

  php-fpm:
    build: docker/php-fpm
    working_dir: /iclinic
    environment:
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
    volumes:
      - '.:/iclinic'
      - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'
