name: code-analysis

on:
  push:
  pull_request:

jobs:
  code-analysis:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
          - name: Setup PHP, with composer and extensions
            uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
            with:
              php-version: '8.0'
              extensions: mbstring, dom, fileinfo, mysql, pdo, redis
              coverage: xdebug

